"""create venue editor tables

Revision ID: 1173a48cf4c7
Revises: 
Create Date: 2026-03-30 14:38:10.624705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1173a48cf4c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('floor_width', sa.Float(), nullable=False),
    sa.Column('floor_depth', sa.Float(), nullable=False),
    sa.Column('floor_height', sa.Float(), nullable=False),
    sa.Column('video_wall_x', sa.Float(), nullable=False),
    sa.Column('video_wall_y', sa.Float(), nullable=False),
    sa.Column('video_wall_z', sa.Float(), nullable=False),
    sa.Column('video_wall_width', sa.Float(), nullable=False),
    sa.Column('video_wall_height', sa.Float(), nullable=False),
    sa.Column('video_wall_depth', sa.Float(), nullable=False),
    sa.Column('video_wall_locked', sa.Boolean(), nullable=False),
    sa.Column('manual_dimmer_supported', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_slug'), 'venues', ['slug'], unique=True)
    op.create_table('fixtures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('venue_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('fixture_type', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('address', sa.Integer(), nullable=False),
    sa.Column('universe', sa.String(length=32), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('rotation_x', sa.Float(), nullable=False),
    sa.Column('rotation_y', sa.Float(), nullable=False),
    sa.Column('rotation_z', sa.Float(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixtures_fixture_type'), 'fixtures', ['fixture_type'], unique=False)
    op.create_index(op.f('ix_fixtures_venue_id'), 'fixtures', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixtures_venue_id'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_fixture_type'), table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_index(op.f('ix_venues_slug'), table_name='venues')
    op.drop_table('venues')
    # ### end Alembic commands ###
