name: Run Pytest

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            portaudio19-dev \
            python3-dev \
            libasound2-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libxrandr2 \
            libxinerama1 \
            libxcursor1 \
            libxi6 \
            libxext6 \
            libxfixes3 \
            libegl1-mesa-dev \
            libgles2-mesa-dev \
            xvfb

      - name: Install Poetry
        run: pipx install poetry

      - name: Configure Poetry cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('pyproject.toml', 'poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run tests
        env:
          DISPLAY: ":99"
          LIBGL_ALWAYS_SOFTWARE: "1"
          MESA_GL_VERSION_OVERRIDE: "3.3"
        run: xvfb-run -a -s "-screen 0 1024x768x24" poetry run python -m pytest

